### ISSUE TITLE
Refactor Actions should use Components

### ISSUE THREAD

**Issue by projektorkraft** [projektorkraft/Golem#12]

**Comment by zwarn** [comment]
Bisher wurde die Module Klasse als ui-Object behandelt und war ein MonoBehavior. Für das Refactoring hab ich Module in die schöne saubere Backend-Welt geholt und musste dabei ein bisschen auf der UI-Seite kaputt machen. Die Liste der möglichen Kommandos hab ich retten können. Den eigenen Spriterenderer hat es aber verloren. Sowas muss in einem zugehörigen Ui-Objekt gemacht werden.
