### ISSUE TITLE
Make Recipes exchangeable

### ISSUE THREAD

**Issue by projektorkraft** [projektorkraft/Golem#13]
We have to enable the exchange of recipes at workstations. 

- [ ] Commands with parameters
 - [x] UI for workstations
 - [x] Create groups for recipes
 - [x] Filter for groups of recipes
 - [ ] Filter for "known" recipes

**Comment by zwarn** [comment]
Als (bevorzugte) Alternative das Rezept an dem gearbeitet werden soll an das Work-Command hängen.

**Comment by zwarn** [comment]
WorkCommands kennen jetzt ihr Rezept und dauern entsprechend lange. HumanHands and GolemHands haben einen Workspeed Faktor

**Comment by projektorkraft** [comment]
This is done. Issues for open points later.
